"""Agent subsystem."""

from nahida_bot.agent.context import ContextBudget, ContextBuilder, ContextMessage
from nahida_bot.agent.loop import (
    AgentLoop,
    AgentLoopConfig,
    AgentRunResult,
    ToolExecutionResult,
    ToolExecutor,
)
from nahida_bot.agent.memory import (
    ConversationTurn,
    MemoryRecord,
    MemoryStore,
    SQLiteMemoryStore,
    extract_keywords,
)
from nahida_bot.agent.metrics import (
    ContextPruneRecord,
    MetricsCollector,
    ProviderCallRecord,
    ToolCallRecord,
    Trace,
)
from nahida_bot.agent.providers import (
    ChatProvider,
    ModelRouter,
    OpenAICompatibleProvider,
    ProviderAuthError,
    ProviderBadResponseError,
    ProviderDescriptor,
    ProviderError,
    ProviderRateLimitError,
    ProviderResponse,
    ProviderTimeoutError,
    ProviderTransportError,
    ReasoningPolicy,
    RoutedModel,
    TokenUsage,
    ToolCall,
    ToolDefinition,
    create_provider,
    extract_think_tags,
    get_provider_class,
    list_providers,
    register_provider,
)
from nahida_bot.agent.tokenization import (
    CharacterEstimateTokenizer,
    CompositeTokenizer,
    HeuristicTokenizer,
    Tokenizer,
)

__all__ = [
    "AgentLoop",
    "AgentLoopConfig",
    "AgentRunResult",
    "CharacterEstimateTokenizer",
    "ChatProvider",
    "CompositeTokenizer",
    "ContextBudget",
    "ContextBuilder",
    "ContextMessage",
    "ContextPruneRecord",
    "ConversationTurn",
    "HeuristicTokenizer",
    "MemoryRecord",
    "MemoryStore",
    "MetricsCollector",
    "ModelRouter",
    "OpenAICompatibleProvider",
    "ProviderAuthError",
    "ProviderBadResponseError",
    "ProviderCallRecord",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderRateLimitError",
    "ProviderResponse",
    "ProviderTimeoutError",
    "ProviderTransportError",
    "ReasoningPolicy",
    "RoutedModel",
    "SQLiteMemoryStore",
    "TokenUsage",
    "ToolCall",
    "ToolCallRecord",
    "ToolDefinition",
    "ToolExecutionResult",
    "ToolExecutor",
    "Tokenizer",
    "Trace",
    "create_provider",
    "extract_keywords",
    "extract_think_tags",
    "get_provider_class",
    "list_providers",
    "register_provider",
]
