import type { DisplayMotion } from "./displayPlan";
import {
  createDefaultModelPerformanceProfile,
  type ModelPerformanceProfile,
} from "./modelPerformanceProfile";
import type {
  Live2DExpressionMap,
  Live2DModelManifest,
  Live2DMotionTarget,
} from "./live2d";
import {
  desktopWindowDefaults,
  petTriggerDefaults,
  ttsDefaults,
} from "@/config/desktopRuntimeDefaults";

export type PerformanceMode = "power_saver" | "balanced" | "active";
export type PetWindowEdge = "left" | "right" | "top" | "bottom";
export type InteractionMode = "click_through" | "interactive";

export interface DesktopWindowState {
  width: number;
  height: number;
  x: number | null;
  y: number | null;
  edge: PetWindowEdge;
  exposedPx: number;
  alwaysOnTop: boolean;
  clickThrough: boolean;
  interactionMode: InteractionMode;
}

export interface ModelMappingConfig {
  modelId: string;
  expressionMap: Live2DExpressionMap;
  motionMap: Partial<Record<DisplayMotion, Live2DMotionTarget>>;
  lipSync: {
    enabled: boolean;
    parameterIds: string[];
  };
  scale: number;
  offsetX: number;
  offsetY: number;
  edgeExposedPx: number;
  performanceProfile: ModelPerformanceProfile;
}

export interface TtsSettings {
  language: string;
  voiceUri: string;
  preferFemale: boolean;
  rate: number;
  pitch: number;
  volume: number;
}

export interface PomodoroSettings {
  enabled: boolean;
  workDurationMinutes: number;
  breakDurationMinutes: number;
  /** How many work+break rounds one start runs before completing. */
  totalRounds: number;
  workStartText: string;
  breakStartText: string;
  /** Reminder when a break ends but more rounds remain. */
  breakEndText: string;
  /** Reminder when the final round's break ends and the run completes. */
  roundsDoneText: string;
  /** Whether phase reminders also request spoken (TTS) playback. */
  speakReminders: boolean;
  /**
   * Whether reminder lines are generated by the Gateway model during the
   * phase runway. Falls back to the static texts on any failure.
   */
  dynamicText: boolean;
  /**
   * Model spec sent with dynamic reminder requests: a Gateway tag such as
   * "primary"/"cheap" or a fixed "provider/model" / bare model name.
   * Empty = the Gateway-side default (webapi.generate.model, then the
   * primary tag, then the default provider).
   */
  dynamicTextModel: string;
}

export interface PetTriggerSettings {
  /** Cursor distance (physical px) that wakes the hidden pet into peek. */
  wakeDistancePx: number;
  /** Cursor distance (physical px) beyond which a peeking pet hides again. */
  hideDistancePx: number;
  /** Retreat to the edge after the pet stayed emerged for this long. */
  autoRetreatMs: number;
  /** Exit chat (and click-through again) after this much inactivity. */
  chatIdleTimeoutMs: number;
}

export const pomodoroDefaults: PomodoroSettings = {
  enabled: false,
  workDurationMinutes: 25,
  breakDurationMinutes: 5,
  totalRounds: 1,
  workStartText: "专注时间开始，加油哦～",
  breakStartText: "休息一下吧，辛苦了～",
  breakEndText: "休息结束，我们继续下一轮吧～",
  roundsDoneText: "番茄轮次全部完成啦，辛苦了，好好放松一下吧～",
  speakReminders: true,
  dynamicText: false,
  dynamicTextModel: "",
};

export interface LocalDesktopConfig {
  selectedModelId: string;
  modelConfigs: Record<string, ModelMappingConfig>;
  windowState: DesktopWindowState;
  performanceMode: PerformanceMode;
  ttsSettings: TtsSettings;
  petTriggers: PetTriggerSettings;
  motionDataCollectionEnabled: boolean;
}

export function modelMappingConfigFromManifest(
  manifest: Live2DModelManifest,
): ModelMappingConfig {
  return {
    modelId: manifest.id,
    expressionMap: { ...manifest.emotionMap },
    motionMap: { ...manifest.motionMap },
    lipSync: {
      enabled: manifest.lipSync.enabled,
      parameterIds: [...manifest.lipSync.parameterIds],
    },
    scale: manifest.layout.scale,
    offsetX: manifest.layout.offsetX,
    offsetY: manifest.layout.offsetY,
    edgeExposedPx: manifest.layout.edgeExposedPx,
    performanceProfile:
      manifest.performanceProfile ??
      createDefaultModelPerformanceProfile(manifest.id),
  };
}

export function createDefaultLocalDesktopConfig(
  manifest: Live2DModelManifest,
  manifests: Live2DModelManifest[] = [manifest],
): LocalDesktopConfig {
  return {
    selectedModelId: manifest.id,
    modelConfigs: Object.fromEntries(
      manifests.map((candidate) => [
        candidate.id,
        modelMappingConfigFromManifest(candidate),
      ]),
    ),
    windowState: {
      width: desktopWindowDefaults.width,
      height: desktopWindowDefaults.height,
      x: null,
      y: null,
      edge: desktopWindowDefaults.edge,
      exposedPx: desktopWindowDefaults.exposedPx,
      alwaysOnTop: desktopWindowDefaults.alwaysOnTop,
      clickThrough: desktopWindowDefaults.clickThrough,
      interactionMode: desktopWindowDefaults.interactionMode,
    },
    performanceMode: desktopWindowDefaults.performanceMode,
    ttsSettings: { ...ttsDefaults },
    petTriggers: { ...petTriggerDefaults },
    motionDataCollectionEnabled: true,
  };
}

export function configuredModelFromManifest(
  manifest: Live2DModelManifest,
  config: ModelMappingConfig,
): Live2DModelManifest {
  return {
    ...manifest,
    emotionMap: { ...config.expressionMap },
    motionMap: { ...config.motionMap },
    lipSync: {
      enabled: config.lipSync.enabled,
      parameterIds: [...config.lipSync.parameterIds],
    },
    layout: {
      scale: config.scale,
      offsetX: config.offsetX,
      offsetY: config.offsetY,
      edgeExposedPx: config.edgeExposedPx,
    },
    performanceProfile: config.performanceProfile,
  };
}
