"""Commit message validator for pre-commit commit-msg stage.

Validates the commit title against the Conventional Commits spec defined in
.github/instructions/commits.instructions.md.
"""

from __future__ import annotations

import re
import sys

# --- Allowed values from commits.instructions.md ---

TYPES = frozenset({"feat", "fix", "docs", "style", "refactor", "test", "chore"})
SCOPE_REQUIRED_TYPES = frozenset({"feat", "fix", "refactor", "test"})
SCOPE_FORBIDDEN_TYPES = frozenset({"docs", "style", "chore"})

MODULE_SCOPES = frozenset(
    {
        "agent",
        "channel",
        "cli",
        "core",
        "db",
        "gateway",
        "node",
        "plugins",
        "providers",
        "workspace",
        # memory maps to agent/memory/ but is listed as a separate scope
        "memory",
    }
)

CROSSCUT_SCOPES = frozenset({"ci", "tests"})
ALLOWED_SCOPES = MODULE_SCOPES | CROSSCUT_SCOPES

# ci is also allowed as a standalone type (without parentheses)
CI_STANDALONE_RE = re.compile(r"^ci:\s+\S")

# <type>(<scope>): <description>
TITLE_RE = re.compile(
    r"^(?P<type>[a-z][a-z-]*[a-z])"
    r"(?:\((?P<scope>[a-z][a-z-]*[a-z])\))?: "
    r"(?P<desc>\S.*)$"
)

_LINE_LENGTH_LIMIT = 72


def _fail(msg: str):
    print(f"commit-msg: {msg}", file=sys.stderr)
    return 1


def main():
    if len(sys.argv) < 2:
        return _fail("No commit message file path provided.")

    msg_path = sys.argv[1]
    lines = None
    try:
        with open(msg_path, encoding="utf-8") as fh:
            lines = fh.readlines()
    except OSError as exc:
        return _fail(f"Cannot read commit message file: {exc}")

    if not lines:
        return _fail("Commit message is empty.")

    title = lines[0].rstrip("\n")

    # Skip merge / squash / revert commits generated by git itself
    if title.startswith(("Merge ", "Squashed ", "Revert ")):
        return 0

    # --- ci: standalone type ---
    if CI_STANDALONE_RE.match(title):
        if len(title) > _LINE_LENGTH_LIMIT:
            return _fail(
                f"Title line is {len(title)} characters (max {_LINE_LENGTH_LIMIT}). "
                "Wrap the description more tightly."
            )
        return 0

    m = TITLE_RE.match(title)
    if m is None:
        return _fail(
            "Title does not match conventional commit format.\n"
            "  Expected: <type>(<scope>): <description>\n"
            "  Examples:\n"
            "    feat(channel): add message parsing for QQ platform\n"
            "    fix(memory): handle malformed JSON correctly\n"
            "    docs: update README with API examples\n"
            "    ci: add commit-msg validation hook"
        )

    commit_type = m.group("type")
    scope = m.group("scope")
    desc = m.group("desc")

    # --- Validate type ---
    if commit_type not in TYPES:
        return _fail(
            f'Unknown type "{commit_type}". Must be one of: {", ".join(sorted(TYPES))}'
        )

    # --- Validate scope presence ---
    if commit_type in SCOPE_REQUIRED_TYPES and scope is None:
        return _fail(
            f'Type "{commit_type}" requires a scope.\n'
            f"  Allowed scopes: {', '.join(sorted(ALLOWED_SCOPES))}"
        )

    if commit_type in SCOPE_FORBIDDEN_TYPES and scope is not None:
        return _fail(
            f'Type "{commit_type}" must not have a scope. Use "<type>: <desc>" format.'
        )

    # --- Validate scope value ---
    if scope is not None and scope not in ALLOWED_SCOPES:
        return _fail(
            f'Unknown scope "{scope}". Allowed: {", ".join(sorted(ALLOWED_SCOPES))}'
        )

    # --- Length check ---
    if len(title) > _LINE_LENGTH_LIMIT:
        return _fail(
            f"Title line is {len(title)} characters (max {_LINE_LENGTH_LIMIT}). "
            "Wrap the description more tightly."
        )

    # --- Quick sanity: description should start with lowercase ---
    if desc and desc[0].isupper():
        print(
            "commit-msg: warning: description starts with uppercase "
            "(prefer lowercase imperative)",
            file=sys.stderr,
        )

    # --- Blank line after title ---
    if len(lines) > 1 and lines[1].strip() != "":
        print(
            "commit-msg: warning: second line should be blank "
            "(separate title from body)",
            file=sys.stderr,
        )

    return 0


if __name__ == "__main__":
    sys.exit(main())
