"""Interactive bootstrap / first-run configuration wizard.

Generates a minimal, working ``config.yaml`` + ``.env`` from a few prompts, so
new deployments don't have to edit the 500-line reference config. Reentrant:
when run against an existing config it only fills gaps instead of clobbering,
and edits the file through the comment-preserving YAML editor so hand-written
notes survive the run.

Usage::

    nahida-bot bootstrap                 # interactive, fresh or fix-missing
    nahida-bot bootstrap --fix-missing   # never overwrite existing values
    nahida-bot bootstrap --non-interactive  # write a skeleton from defaults/env
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import typer
import yaml
from rich.console import Console
from rich.prompt import Confirm, Prompt

from nahida_bot.agent.providers.catalog import (
    PROVIDER_PRESETS,
    preset_with_base_url,
)
from nahida_bot.cli.provider_setup import pick_labelled, pick_provider_preset
from nahida_bot.core.config import find_config_yaml, find_env_path, load_settings
from nahida_bot.core.yaml_edit import (
    YamlEditError,
    document_to_text,
    load_yaml_document,
    save_document,
    upsert_path,
)

console = Console()

bootstrap_app = typer.Typer(help="Interactive first-run configuration wizard")


# ---------------------------------------------------------------------------
# Channel templates
# ---------------------------------------------------------------------------


@dataclass(slots=True, frozen=True)
class ChannelTemplate:
    label: str
    key: str  # top-level config key
    fields: dict[str, str]  # config field -> ${ENV} reference
    secrets: dict[str, str]  # env var name -> human label
    extras: dict[str, Any] = field(default_factory=dict)


_CHANNEL_PRESETS: dict[str, ChannelTemplate] = {
    "telegram": ChannelTemplate(
        label="Telegram Bot",
        key="telegram",
        fields={"bot_token": "${TELEGRAM_BOT_TOKEN:}"},
        secrets={"TELEGRAM_BOT_TOKEN": "Telegram bot token (from @BotFather)"},
        extras={"enabled": True},
    ),
    "milky": ChannelTemplate(
        label="Milky QQ (Lagrange.Milky)",
        key="milky",
        fields={
            "base_url": "http://127.0.0.1:3000",
            "access_token": "${MILKY_ACCESS_TOKEN:}",
        },
        secrets={"MILKY_ACCESS_TOKEN": "Milky access token"},
        extras={"enabled": True, "group_trigger_mode": "mention"},
    ),
    "onebot": ChannelTemplate(
        label="OneBot v11 (NapCat/Lagrange/LLOneBot)",
        key="onebot",
        fields={
            "ws_url": "${ONEBOT_WS_URL:ws://127.0.0.1:3001}",
            "ws_access_token": "${ONEBOT_ACCESS_TOKEN:}",
        },
        secrets={
            "ONEBOT_ACCESS_TOKEN": "OneBot access token (optional)",
        },
        extras={"enabled": True, "protocol_version": "v11"},
    ),
}


# Provider presets live in nahida_bot.agent.providers.catalog so bootstrap and
# `auth login` stamp identical entries; base_url / models are sensible
# defaults and the api key always lives in .env behind ${VAR} interpolation.


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _read_yaml(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    try:
        with path.open("r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError:
        return {}
    return data if isinstance(data, dict) else {}


def _read_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        return {}
    out: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        out[k.strip()] = v.strip().strip('"').strip("'")
    return out


def _write_yaml(path: Path, data: dict[str, Any]) -> None:
    header = (
        "# Nahida Bot configuration — generated by `nahida-bot bootstrap`.\n"
        "# Edit freely; secrets live in .env and are referenced via ${VAR}.\n"
        "# Run `nahida-bot config schema` for the full list of options.\n\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    body = yaml.safe_dump(data, sort_keys=False, allow_unicode=True, width=78)
    path.write_text(header + body, encoding="utf-8")


def _write_env(path: Path, env: dict[str, str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Secrets for Nahida Bot — generated by `nahida-bot bootstrap`.",
        "# This file is gitignored; keep it out of version control.",
        "",
    ]
    for k, v in env.items():
        lines.append(f'{k}="{v}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


# Capability → required model tag mapping. A bootstrapped minimal config only
# carries [primary], so we surface which optional subsystems are left without a
# target model and point the user at the config reference.
_CAPABILITY_TAGS = [
    ("对话", "primary", "基础聊天（已配置）"),
    ("图片理解", "vision", "收发图片；可加到某个多模态模型上"),
    ("记忆向量检索", "embedding", "memory 向量/混合检索，需显式开启 memory.embedding"),
    ("记忆整理 dreaming", "memory", "更省的 dreaming 模型；不配则退回会话模型"),
]


def _collect_model_tags(merged: dict[str, Any]) -> set[str]:
    tags: set[str] = set()
    for entry in (merged.get("providers") or {}).values():
        if not isinstance(entry, dict):
            continue
        for model in entry.get("models") or []:
            if isinstance(model, dict):
                tags.update(model.get("tags") or [])
    return tags


def _print_capability_checklist(merged: dict[str, Any]) -> None:
    tags = _collect_model_tags(merged)
    console.print("[bold]能力检查（按 model tag）：[/bold]")
    for label, tag, hint in _CAPABILITY_TAGS:
        if tag in tags:
            console.print(f"  [green]✓[/green] {label}  [dim]({tag})[/dim]")
        elif tag == "primary":
            console.print(f"  [green]✓[/green] {label}  [dim]({tag})[/dim]")
        else:
            console.print(
                f"  [yellow]~[/yellow] {label}  [dim]缺 [cyan]{tag}[/cyan] tag — {hint}[/dim]"
            )
    console.print(
        "[dim]以上「~」项不影响启动，只是对应能力会降级或关闭。"
        "补 tag 见 [cyan]docs/guide/configuration.md[/cyan] 的 providers.models[].tags。[/dim]"
    )


def _validate_content(content: str, target_env: Path) -> None:
    """Validate candidate config text through the real settings loader."""

    tmp_yaml = Path(str(target_env) + ".tmp.bootstrap.yaml")
    try:
        tmp_yaml.write_text(content, encoding="utf-8")
        load_settings(
            config_yaml=str(tmp_yaml),
            env_path=str(target_env) if target_env.is_file() else None,
        )
    except Exception as exc:
        console.print(f"[bold red]Generated config failed validation:[/bold red] {exc}")
        raise typer.Exit(1) from exc
    finally:
        tmp_yaml.unlink(missing_ok=True)


# ---------------------------------------------------------------------------
# Main command
# ---------------------------------------------------------------------------


@bootstrap_app.callback(invoke_without_command=True)
def bootstrap(
    ctx: typer.Context,
    config_yaml: str | None = typer.Option(
        None,
        "--config-yaml",
        "--config",
        "-c",
        help="Target config.yaml path (default: ./config.yaml)",
    ),
    env_path: str | None = typer.Option(
        None, "--env", help="Target .env path (default: ./.env)"
    ),
    fix_missing: bool = typer.Option(
        False,
        "--fix-missing",
        help="Only fill gaps; never overwrite values already present.",
    ),
    non_interactive: bool = typer.Option(
        False,
        "--non-interactive",
        help="Write a minimal skeleton without prompting (for scripts/Docker).",
    ),
) -> None:
    """Generate a minimal working config.yaml + .env."""
    target_yaml = Path(config_yaml or find_config_yaml(None) or "config.yaml")
    target_env = Path(env_path or find_env_path(None) or ".env")

    existing_yaml = _read_yaml(target_yaml)
    existing_env = _read_env(target_env)

    has_config = bool(existing_yaml)
    if has_config:
        console.print(
            f"[yellow]Found existing {target_yaml}.[/yellow] "
            + ("Preserving existing values (--fix-missing)." if fix_missing else "")
        )

    # --- provider selection ---
    providers_section: dict[str, Any] = dict(existing_yaml.get("providers") or {})
    touched_providers: dict[str, dict[str, Any]] = {}
    new_env: dict[str, str] = {}
    default_provider = existing_yaml.get("default_provider", "")

    if non_interactive:
        if not providers_section:
            preset_key = os.environ.get("NAHIDA_BOOTSTRAP_PROVIDER", "deepseek")
            preset = PROVIDER_PRESETS[preset_key]
            pid = os.environ.get("NAHIDA_BOOTSTRAP_PROVIDER_ID", "main")
            providers_section[pid] = preset.render_entry()
            touched_providers[pid] = providers_section[pid]
            default_provider = pid
            new_env[preset.key_env] = os.environ.get(preset.key_env, "")
    else:
        if not providers_section or Confirm.ask(
            "Configure an LLM provider?", default=True
        ):
            preset_key = pick_provider_preset(
                "Choose an LLM provider preset:",
                default="deepseek",
                console=console,
            )
            preset = PROVIDER_PRESETS[preset_key]
            pid = Prompt.ask("Provider id (the key in config)", default=preset_key)
            if preset.base_url and not fix_missing:
                base = Prompt.ask("Base URL", default=preset.base_url)
                preset_b = preset_with_base_url(preset, base)
            else:
                preset_b = preset
            key_value = ""
            if preset.needs_key:
                key_value = Prompt.ask(preset.key_label, password=True, default="")
            if pid not in providers_section or not fix_missing:
                providers_section[pid] = preset_b.render_entry()
                touched_providers[pid] = providers_section[pid]
            if preset.needs_key:
                new_env[preset.key_env] = key_value
            default_provider = default_provider or pid

    # --- channel selection ---
    channels_section: dict[str, dict[str, Any]] = {}
    for k, v in existing_yaml.items():
        if k in _CHANNEL_PRESETS and isinstance(v, dict):
            channels_section[k] = v
    touched_channels: dict[str, dict[str, Any]] = {}

    if non_interactive:
        desired = [
            c.strip()
            for c in os.environ.get("NAHIDA_BOOTSTRAP_CHANNELS", "").split(",")
            if c.strip()
        ]
        for ch_key in desired:
            if ch_key in _CHANNEL_PRESETS and (
                ch_key not in channels_section or not fix_missing
            ):
                tpl = _CHANNEL_PRESETS[ch_key]
                channels_section[ch_key] = {**tpl.extras, **tpl.fields}
                touched_channels[ch_key] = channels_section[ch_key]
                for env_name in tpl.secrets:
                    new_env[env_name] = os.environ.get(env_name, "")
    else:
        while True:
            remaining = {
                k: v for k, v in _CHANNEL_PRESETS.items() if k not in channels_section
            }
            if not remaining:
                console.print("[dim]All known channels are configured.[/dim]")
                break
            if not Confirm.ask(
                "Configure a messaging channel?", default=not channels_section
            ):
                break
            ch_key = pick_labelled(
                remaining,
                "Choose a channel to add:",
                default=next(iter(remaining)),
                console=console,
            )
            tpl = _CHANNEL_PRESETS[ch_key]
            channel_entry: dict[str, Any] = dict(tpl.extras)
            for env_name, label in tpl.secrets.items():
                val = Prompt.ask(label, password=True, default="")
                new_env[env_name] = val
            channel_entry.update(tpl.fields)
            channels_section[ch_key] = channel_entry
            touched_channels[ch_key] = channel_entry

    # --- assemble, validate and write ---
    framework_defaults: dict[str, Any] = {
        "app_name": "Nahida Bot",
        "db_path": "./data/nahida.db",
        "workspace_base_dir": "./data/workspace",
        "plugin_paths": ["./plugins"],
    }

    try:
        if has_config:
            # Existing (possibly hand-edited) file: targeted, comment-
            # preserving edits instead of a destructive full rewrite.
            doc = load_yaml_document(target_yaml)
            for pid, entry in touched_providers.items():
                upsert_path(doc, ["providers", pid], entry)
            if default_provider and doc.get("default_provider") != default_provider:
                upsert_path(doc, ["default_provider"], default_provider)
            for ch_key, ch_val in touched_channels.items():
                upsert_path(doc, [ch_key], ch_val)
            for key, val in framework_defaults.items():
                if key not in doc:
                    doc[key] = val
            content = document_to_text(doc)
            _validate_content(content, target_env)
            backup_path = save_document(doc, target_yaml)
            if backup_path:
                console.print(f"[dim]Backup written: {backup_path}[/dim]")
            merged = yaml.safe_load(content)
        else:
            merged = dict(existing_yaml)
            merged["providers"] = providers_section
            if default_provider:
                merged["default_provider"] = default_provider
            for ch_key, ch_val in channels_section.items():
                merged[ch_key] = ch_val
            merged.update(
                {k: v for k, v in framework_defaults.items() if k not in merged}
            )
            body = yaml.safe_dump(merged, sort_keys=False, allow_unicode=True, width=78)
            header = (
                "# Nahida Bot configuration — generated by `nahida-bot bootstrap`.\n"
                "# Edit freely; secrets live in .env and are referenced via ${VAR}.\n"
                "# Run `nahida-bot config schema` for the full list of options.\n\n"
            )
            _validate_content(header + body, target_env)
            _write_yaml(target_yaml, merged)
    except YamlEditError as exc:
        console.print(f"[bold red]Cannot edit {target_yaml}: {exc}[/bold red]")
        raise typer.Exit(1) from exc

    # Merge new secrets into existing env (preserve untouched entries, keep
    # empty placeholders so the user can see what to fill in).
    final_env = {**existing_env, **new_env}
    if final_env or target_env.is_file():
        _write_env(target_env, final_env)

    console.print(
        f"\n[bold green]Done.[/bold green]\n"
        f"  config: [cyan]{target_yaml}[/cyan]\n"
        f"  env:    [cyan]{target_env}[/cyan]"
    )
    provider_count = len(merged.get("providers", {}))
    channel_count = sum(
        1 for k in merged if k in _CHANNEL_PRESETS and merged[k].get("enabled")
    )
    console.print(f"  providers: {provider_count}  channels: {channel_count}\n")
    if not provider_count:
        console.print(
            "[yellow]No provider configured — run `nahida-bot bootstrap` again "
            "or edit config.yaml before starting the bot.[/yellow]"
        )
    else:
        _print_capability_checklist(merged)
    console.print(
        "Next: edit [cyan].env[/cyan] to fill in secrets, then "
        "[cyan]nahida-bot doctor[/cyan] to verify, and "
        "[cyan]nahida-bot start[/cyan] to launch."
    )
