"""Core application infrastructure."""

from nahida_bot.core.exceptions import (
    NahidaBotError,
    ConfigError,
    ApplicationError,
    StartupError,
    CommunicationError,
    PluginError,
    PermissionDenied,
    PluginLoadError,
    PluginStateError,
)
from nahida_bot.core.events import (
    Event,
    EventBus,
    EventContext,
    PublishResult,
    Subscription,
    AppInitializing,
    AppStarted,
    AppStopping,
    AppStopped,
    PluginLoaded,
    PluginEnabled,
    PluginDisabled,
    PluginUnloaded,
    PluginErrorOccurred,
    PluginPayload,
    PluginErrorPayload,
)
from nahida_bot.core.logging import configure_logging

__all__ = [
    "NahidaBotError",
    "ConfigError",
    "ApplicationError",
    "StartupError",
    "CommunicationError",
    "PluginError",
    "PermissionDenied",
    "PluginLoadError",
    "PluginStateError",
    "configure_logging",
    "Event",
    "EventBus",
    "EventContext",
    "PublishResult",
    "Subscription",
    "AppInitializing",
    "AppStarted",
    "AppStopping",
    "AppStopped",
    "PluginLoaded",
    "PluginEnabled",
    "PluginDisabled",
    "PluginUnloaded",
    "PluginErrorOccurred",
    "PluginPayload",
    "PluginErrorPayload",
]
